# Site settings
author: Lluvia Frias
title: The Journey of an Onlline Student
header-img: img/home-bg.png
email: lluvi.frias@gmail.com
copyright_name: Lluvia Frias
description: > # this means to ignore newlines until "baseurl:"
  The Sum of All Choices Made
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  ninjaturtle3

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
